defaults: &defaults
  app_name: "320 KBS"
  ftp_path: <%= File.join(Rails.root, 'data', 'ftp') %>
  ftp_server: "320kbs.ru" # адрес ftp сервера
  account_activation_time: 3  # время которе действут ссылка для активации учетной записа, в днях
  delta_index: "1.hour" # Время частичной индексации для сфинкса

  boolean_display:
    true: 'yes'
    false: 'no'

  type_ban:   # Тип бана пользователя
    account_ban: 1
    ip_ban: 2
    value_display:
      1: '<%= I18n.t('type_ban_account') %>'
      2: '<%= I18n.t('type_ban_ip') %>'
    value_for_valid:
      - 1
      - 2
    value_for_options:
      -
        - '<%= I18n.t('type_ban_account') %>'
        - 1
      -
        - '<%= I18n.t('type_ban_ip') %>'
        - 2
development:
  <<: *defaults
  mp3_cut_command: 'mp3cut'
  main_domain: "localhost"
test:
  <<: *defaults
  main_domain: "www.example.com"
cucumber:
  <<: *defaults
  main_domain: "www.example.com"
production:
  <<: *defaults
  mp3_cut_command: '/usr/bin/mp3cut'
  main_domain: "320kbs.ru"

