development:
  web_host: localhost:3000
  email:
    delivery_method: sendmail
    site_admin_email: youremail@example.com
production:
  web_host: 320kbs.ru
  email:
    delivery_method: sendmail
    site_admin_email: support@320kbs.ru
test: &TEST
  web_host: localhost:3000
  email:
    delivery_method: test
    site_admin_email: foo@gmail.com

cucumber:
  <<: *TEST
