development:
  enable_star: true
  min_infix_len: 1
  mem_limit: 128M
  max_matches: 1000000
test:
  enable_star: true
  min_infix_len: 1
  mem_limit: 128M
  max_matches: 1000000
production:
  enable_star: true
  min_infix_len: 1
  mem_limit: 128M
  max_matches: 1000000
