#!/usr/bin/env ruby
=begin rdoc
Загрузка файлов с фтп
=end
require File.expand_path(File.join(File.dirname(__FILE__), '..', 'config', 'environment'))
require 'rubygems'
require 'rb-inotify'
require 'mp3info'
# require 'daemons'
# Daemons.run("#{RAILS_ROOT}/lib/ftp_inotify.rb")
notifier = INotify::Notifier.new

notifier.watch(File.join('/var/www','mp3cms','shared','data','ftp'), :close_write, :moved_to, :recursive) do |event|
  begin
    file_path = event.absolute_name
    file_name = File.basename(event.absolute_name)
    user_email = File.split(File.dirname(event.absolute_name)).last
    tmp_path = File.join(File.dirname(event.absolute_name), "#{file_name}")

    Rails.logger.info '-'*90
    Rails.logger.info "upload file on ftp #{event.absolute_name}"
    if (user = User.find_by_email(user_email))
      # если в данный момент все загрузки на основной сервер - то заливаем на него
      # если какой-то сателлит назначен основным то заливаем на него
      Mp3Info.open(tmp_path) do |mp3|
        title=   mp3.tag.title.try(:to_utf8) || file_name
        author= mp3.tag.author.try(:to_utf8) || "user: - #{user.login}"
      end
      user.tracks.create!({ :data => File.open(tmp_path).binmode, :title => title , :satellite_id => Satellite.f_master.id ,
                                                                  :author => author })
    else
      Rails.logger.error "not found user for email: #{user_email}"
    end
    FileUtils.rm_rf tmp_path
    Rails.logger.info '-'*90
  rescue => e
    puts e
    Rails.logger.error e
    Rails.logger.error  " #{$!.inspect} "
  end
end
notifier.run


