#!/usr/bin/env ruby
# encoding: utf-8
# Загрузка файлов с фтп

require File.expand_path( File.join( File.dirname(__FILE__), '..', 'config', 'environment' ) )
require 'rubygems'
require 'rb-inotify'
require 'mp3info'

notifier = INotify::Notifier.new
watch_path = Settings[:ftp_path]

notifier.watch(watch_path, :close_write, :moved_to, :recursive) do |event|
  begin
    Rails.logger.debug "=========== monitor ftp folder ======================================================"
    puts "=========== monitor ftp folder ======================================================"
    file_path  = event.absolute_name
    file_name  = File.basename(event.absolute_name)
    user_email = File.split(File.dirname(event.absolute_name)).last
    tmp_path   = File.join(File.dirname(event.absolute_name), "#{file_name}")

    Rails.logger.debug '-'*90
    Rails.logger.debug "upload file on ftp #{event.absolute_name}"

    if (user = User.find_by_email(user_email))
      # если в данный момент все загрузки на основной сервер - то заливаем на него
      # если какой-то сателлит назначен основным то заливаем на него

      Mp3Info.open(tmp_path) do |mp3|
        title  = mp3.tag.title.try(:to_utf8) || file_name
        author = mp3.tag.artist.try(:to_utf8) || "user: - #{user.login}"
        track = user.tracks.new({ :data => File.open(tmp_path).binmode,
                                  :title => title ,
                                  :satellite => Satellite.master ,
                                  :author => author })
        if track.valid?
          track.save!
        else
          Rails.logger.debug "track is not valid : #{ track.errors.inspect }"
        end
      end

    else
      Rails.logger.error "not found user for email: #{user_email}"
    end

    FileUtils.rm_rf tmp_path
  rescue => e
    puts e
    Rails.logger.error e
    Rails.logger.error  " #{$!.inspect} "
  end
end

notifier.run


